"""
Django settings for opsmis project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#&&h68p9(e0#$#*%)*c14y5pru^1s5hv$0w2h%hb=-&kcxcmyd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'opsapp.apps.OpsappConfig',
    'DjangoUeditor',# 富文本 编辑
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'opsmis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opsmis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mis',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans' #语言修改为中文

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
#设置静态文件目录和名称
STATIC_URL = '/static/'

#这个是设置静态文件夹目录的路径
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
#设置文件上传路径，图片上传、文件上传都会存放在此目录里
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#
# 首页配置
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# 首页标题
# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
# 首页图标
# SIMPLEUI_HOME_ICON = 'layui-icon-rate'
#LOGO
#SIMPLEUI_LOGO = 'logo.png'
#离线模式
SIMPLEUI_STATIC_OFFLINE = True
#默认主题
SIMPLEUI_DEFAULT_THEME = 'element.css'
# 设置simpleui 点击首页图标跳转的地址
SIMPLEUI_INDEX = 'https://www.88cto.com'
#首页图标
SIMPLEUI_HOME_ICON = 'fa fa-user'
#服务器信息
SIMPLEUI_HOME_INFO = False
#快速操作
SIMPLEUI_HOME_QUICK = True
#最近动作
SIMPLEUI_HOME_ACTION = False
#使用分析
SIMPLEUI_ANALYSIS = False
#菜单
#system_keep保留系统菜单
SYSTEM_KEEP = True
#menu_display 过滤显示菜单和排序功能
MENU_DISPLAY = True
#dynamic 开启动态菜单功能
DYNAMIC = True

# 自定义simpleui 菜单
SIMPLEUI_CONFIG = {
    # 在自定义菜单的基础上保留系统模块
    'system_keep': True,
    #菜单排序和过滤
    'menu_display': ['信息管理', '报表管理', '工作台', '操作间实况', '值班管理', '权限认证'],
    'menus': [{
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': 'auth/user/'
        }]
    },  {
        'name': '报表管理',
        'icon': 'fas fa-chart-area',
        'models': [{
            'name': 'D+批量',
            'url': '/dplusreport',
            'icon': 'fas fa-chart-area'
        }, {
            'name': 'Murex批量',
            'url': '/murexreport',
            'icon': 'fas fa-chart-area'
        }, {
            'name': '关键批量',
            'url': '/majortask',
            'icon': 'fas fa-chart-area'
        }, {
            'name': '重要报表',
            'url': '/majorreport',
            'icon': 'fas fa-chart-area'
        }, {
            'name': '报表示例',
            'url': '/reportdemo',
            'icon': 'fas fa-chart-area'
        }]
    }, {
        'name': '值班管理',
        'icon': 'fas fa-calendar-alt',
        'models': [{
            'name': '操作组值班',
            'url': '/operaduty',
            'icon': 'far fa-calendar-alt'
        }, {
            'name': '运营值班',
            'url': '/opsduty',
            'icon': 'far fa-calendar-alt'
        }]
    }, {
        'name': '操作间实况',
        'icon': 'fas fa-eye',
        'models': [{
            'name': '操作间进出实况',
            'url': '/turnoverlive',
            'icon': 'fas fa-walking'
        }, {
            'name': '操作环境实况',
            'url': '/systemlive',
            'icon': 'fas fa-laptop'
        }, {
            'name': '操作行为实况',
            'url': '/commandlive',
            'icon': 'fas fa-laptop-code'
        }, {
            'name': '批量调度实况',
            'url': '/batchrunlive',
            'icon': 'fas fa-chart-pie'
        }]
    }, {
        'name': '工作台',
        'icon': 'fas fa-desktop',
        'models': [{
            'name': '操作日志',
            'url': '/operlog',
            'icon': 'fas fa-edit'
        }, {
            'name': 'D+',
            'url': '/importdplus',
            'icon': 'fas fa-edit'
        }, {
            'name': 'Murex',
            'url': '/importmurex',
            'icon': 'fas fa-edit'
        }]
    }]
}
# 是否显示默认图标，默认=True
# SIMPLEUI_DEFAULT_ICON = False
# 图标设置，图标参考：
SIMPLEUI_ICON = {
    '信息管理': 'fa fa-th-large',
    '工作信息': 'fa fa-th-list',
    '作业信息':'fa fa-th-list'
}


