# Generated by Django 3.0.3 on 2020-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=20, verbose_name='系统名称')),
                ('sys_desc', models.CharField(max_length=20, verbose_name='系统描述')),
                ('task_name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('task_desc', models.CharField(max_length=20, verbose_name='任务描述')),
                ('task_date', models.DateField(verbose_name='任务日期')),
                ('begin_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('error_msg', models.CharField(default='', max_length=50, verbose_name='异常情况')),
                ('error_user', models.CharField(default='', max_length=20, verbose_name='异常处理人')),
            ],
            options={
                'verbose_name': '作业信息',
                'verbose_name_plural': '作业信息',
            },
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_status',
            field=models.IntegerField(choices=[(0, '未知'), (1, '有效'), (2, '无效')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='job_type',
            field=models.IntegerField(choices=[(0, '未知'), (1, '工作日'), (2, '每天')], default=2, verbose_name='工作类型'),
        ),
    ]
